import operator
from typing import Annotated

from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages
from typing_extensions import NotRequired, TypedDict


class SubtaskFinding(TypedDict):
    subtask: str
    claim: str
    evidence_span: str
    citation_url: str


class Clarification(TypedDict):
    question: str
    answer: str


class TokenUsage(TypedDict):
    """Token usage for a single LLM call, tagged by node + model (cost tracking)."""
    node: str
    model: str
    input_tokens: int
    output_tokens: int
    cached_tokens: int


# WORKING MEMORY (layer 1 of the memory stack):
# Typed LangGraph state — the in-run scratchpad passed between all nodes.
# Persisted per thread_id by the Postgres checkpointer (layer 3).
class ResearchState(TypedDict):
    run_id: str
    query: str
    # User-selected lead model (clarify/plan/synthesize/chat) for this run.
    # Falls back to engine.models.LEAD_MODEL when absent.
    lead_model: NotRequired[str]
    # Questions generated by the clarify node, pending user answers
    clarification_questions: list[str]
    # Chip options for each clarifying question (parallel list)
    clarification_options: list[list[str]]
    # Clarifying questions asked + user answers (human-in-the-loop, layer 3)
    clarifications: list[Clarification]
    # Supervisor's free-text reasoning about how to approach the query (plan node)
    supervisor_thinking: str
    # Short display title for this research, generated by the plan node
    title: str
    # Sub-questions produced by the plan node
    subtasks: list[str]
    # operator.add reducer accumulates findings from all parallel subagents
    findings: Annotated[list[SubtaskFinding], operator.add]
    # Populated by the compact node (context compaction, layer 2)
    summary: str
    # Final cited Markdown report written by the synthesize node
    report: str
    # add_messages reducer enables multi-turn follow-up chat (layer 3)
    messages: Annotated[list[BaseMessage], add_messages]
    # Per-LLM-call token usage across all nodes — powers the cost/usage summary
    token_usage: Annotated[list[TokenUsage], operator.add]
    # Subtask question for each subagent invocation that completed, even if it
    # found zero findings — lets the API mark that subtask "done" in the UI
    # (a finding-derived question would be empty/unmatched in that case).
    processed_subtasks: Annotated[list[str], operator.add]


class SubagentInput(TypedDict):
    """Payload sent to each subagent via Send fan-out. Not the full graph state."""
    question: str
