import operator
from typing import Annotated, Literal

from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages
from typing_extensions import NotRequired, TypedDict


class SubtaskFinding(TypedDict):
    subtask: str
    claim: str
    evidence_span: str
    citation_url: str


class Clarification(TypedDict):
    question: str
    answer: str


class DebateTurn(TypedDict):
    """One turn of the adversarial debate (debate mode)."""
    agent: str    # "advocate" | "skeptic"
    model: str    # which LLM produced this turn (shown in the UI badge)
    round: int    # 1-based; one round = advocate turn + skeptic turn
    content: str


class VerdictRow(TypedDict):
    """One judged category in the debate verdict table (shown in the UI)."""
    category: str    # short label, e.g. "Evidence Quality"
    assessment: str  # one-sentence summary of the judge's reasoning
    winner: str       # "proposition" | "opposition" | "draw"


class DebateVerdict(TypedDict):
    """The lead model's neutral judgment of the finished debate (debate mode)."""
    rows: list[VerdictRow]  # per-category breakdown, rendered as a table in the UI
    winner: str             # overall winner: "proposition" | "opposition" | "draw"
    model: str              # judge model (the run's lead model)


class TokenUsage(TypedDict):
    """Token usage for a single LLM call, tagged by node + model (cost tracking)."""
    node: str
    model: str
    input_tokens: int
    output_tokens: int
    cached_tokens: int


ResearchMode = Literal[
    "single_agent",
    "multi_agent_no_compaction",
    "multi_agent_compaction",
    "multi_agent_verified",
]


# WORKING MEMORY (layer 1 of the memory stack):
# Typed LangGraph state — the in-run scratchpad passed between all nodes.
# Persisted per thread_id by the Postgres checkpointer (layer 3).
class ResearchState(TypedDict):
    run_id: str
    query: str
    # User-selected lead model (clarify/plan/synthesize/chat) for this run.
    # Falls back to engine.models.LEAD_MODEL when absent.
    lead_model: NotRequired[str]
    # Benchmark mode switches graph shape for comparison runs:
    # single agent, multi-agent raw, multi-agent compacted, or verified.
    run_mode: NotRequired[ResearchMode]
    # Questions generated by the clarify node, pending user answers
    clarification_questions: list[str]
    # Chip options for each clarifying question (parallel list)
    clarification_options: list[list[str]]
    # Clarifying questions asked + user answers (human-in-the-loop, layer 3)
    clarifications: list[Clarification]
    # Supervisor's free-text reasoning about how to approach the query (plan node)
    supervisor_thinking: str
    # Short display title for this research, generated by the plan node
    title: str
    # Sub-questions produced by the plan node
    subtasks: list[str]
    # operator.add reducer accumulates findings from all parallel subagents
    findings: Annotated[list[SubtaskFinding], operator.add]
    # Populated by the compact node (context compaction, layer 2)
    summary: str
    # Debate mode: when true, two adversarial agents argue over the compacted
    # findings before synthesis (advocate vs skeptic, debate_rounds rounds)
    debate_mode: NotRequired[bool]
    debate_rounds: NotRequired[int]
    # Cross-provider debater models — fall back to lead_model when absent
    advocate_model: NotRequired[str]
    skeptic_model: NotRequired[str]
    # operator.add reducer accumulates turns; kept after the run (small) so
    # GET /runs/{id} can restore the debate panel
    debate_turns: Annotated[list[DebateTurn], operator.add]
    # The lead model's neutral verdict on who won the debate, set by the
    # judge_debate node after the final round
    debate_verdict: NotRequired[DebateVerdict]
    # Debate-driven gap research: follow-up questions distilled from the
    # skeptic's unresolved objections, researched in a second subagent round
    gap_subtasks: NotRequired[list[str]]
    # Final cited Markdown report written by the synthesize node
    report: str
    # add_messages reducer enables multi-turn follow-up chat (layer 3)
    messages: Annotated[list[BaseMessage], add_messages]
    # Per-LLM-call token usage across all nodes — powers the cost/usage summary
    token_usage: Annotated[list[TokenUsage], operator.add]
    # Subtask question for each subagent invocation that completed, even if it
    # found zero findings — lets the API mark that subtask "done" in the UI
    # (a finding-derived question would be empty/unmatched in that case).
    processed_subtasks: Annotated[list[str], operator.add]


class SubagentInput(TypedDict):
    """Payload sent to each subagent via Send fan-out. Not the full graph state."""
    question: str
