"""add title to research_runs

Revision ID: 7a885b67938e
Revises: 8dcfb8f02be3
Create Date: 2026-06-11 15:51:31.840008

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = '7a885b67938e'
down_revision: Union[str, None] = '8dcfb8f02be3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_runs', sa.Column('title', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_runs', 'title')
    # ### end Alembic commands ###
