from __future__ import annotations

import uuid
from datetime import datetime
from typing import Optional

from sqlalchemy import DateTime, Float, ForeignKey, Integer, String, Text, UniqueConstraint
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship
from sqlalchemy.sql import func


def _uuid() -> str:
    return str(uuid.uuid4())


class Base(DeclarativeBase):
    pass


class ResearchRun(Base):
    __tablename__ = "research_runs"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=_uuid)
    query: Mapped[str] = mapped_column(Text, nullable=False)
    # Short display title generated by the plan node (3-6 words); falls back to
    # the raw query in the UI until the plan node completes.
    title: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    # Anonymous browser-generated id (X-Client-Id header) scoping per-visitor listings.
    client_id: Mapped[Optional[str]] = mapped_column(String, nullable=True, index=True)
    # pending | awaiting_clarification | running | done | failed
    status: Mapped[str] = mapped_column(String, nullable=False, default="pending")
    # {questions: [...], answers: [...]} populated during human-in-the-loop clarification
    clarifications: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)
    # {subtasks: [...]} set by the plan node
    plan: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)
    stats: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)
    started_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    finished_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)

    subtasks: Mapped[list[Subtask]] = relationship(back_populates="run", cascade="all, delete-orphan")
    sources: Mapped[list[Source]] = relationship(back_populates="run", cascade="all, delete-orphan")
    report: Mapped[Optional[Report]] = relationship(back_populates="run", uselist=False, cascade="all, delete-orphan")
    eval_reports: Mapped[list[EvalReportRecord]] = relationship(
        back_populates="run", cascade="all, delete-orphan"
    )


class Subtask(Base):
    __tablename__ = "subtasks"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=_uuid)
    run_id: Mapped[str] = mapped_column(String, ForeignKey("research_runs.id", ondelete="CASCADE"), nullable=False)
    question: Mapped[str] = mapped_column(Text, nullable=False)
    # pending | running | done | failed
    status: Mapped[str] = mapped_column(String, nullable=False, default="pending")

    run: Mapped[ResearchRun] = relationship(back_populates="subtasks")
    findings: Mapped[list[Finding]] = relationship(back_populates="subtask", cascade="all, delete-orphan")


class Source(Base):
    __tablename__ = "sources"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=_uuid)
    run_id: Mapped[str] = mapped_column(String, ForeignKey("research_runs.id", ondelete="CASCADE"), nullable=False)
    url: Mapped[str] = mapped_column(Text, nullable=False)
    title: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    fetched_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    run: Mapped[ResearchRun] = relationship(back_populates="sources")
    findings: Mapped[list[Finding]] = relationship(back_populates="source")


class Finding(Base):
    __tablename__ = "findings"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=_uuid)
    subtask_id: Mapped[str] = mapped_column(String, ForeignKey("subtasks.id", ondelete="CASCADE"), nullable=False)
    source_id: Mapped[str] = mapped_column(String, ForeignKey("sources.id", ondelete="SET NULL"), nullable=True)
    # Mirrors the Pydantic Finding schema in engine/extraction.py
    claim: Mapped[str] = mapped_column(Text, nullable=False)
    evidence_span: Mapped[str] = mapped_column(Text, nullable=False)
    citation_url: Mapped[str] = mapped_column(Text, nullable=False)

    subtask: Mapped[Subtask] = relationship(back_populates="findings")
    source: Mapped[Optional[Source]] = relationship(back_populates="findings")


class Report(Base):
    __tablename__ = "reports"
    __table_args__ = (UniqueConstraint("run_id"),)

    id: Mapped[str] = mapped_column(String, primary_key=True, default=_uuid)
    run_id: Mapped[str] = mapped_column(String, ForeignKey("research_runs.id", ondelete="CASCADE"), nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    structured: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)

    run: Mapped[ResearchRun] = relationship(back_populates="report")


class EvalReportRecord(Base):
    """Persisted result of running the Phase 4 eval harness (eval/) against a run."""

    __tablename__ = "eval_reports"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=_uuid)
    run_id: Mapped[str] = mapped_column(
        String, ForeignKey("research_runs.id", ondelete="CASCADE"), nullable=False
    )
    # Denormalized from the parent run so dashboard listing doesn't need a join.
    client_id: Mapped[Optional[str]] = mapped_column(String, nullable=True, index=True)
    # Denormalized from EvalReport.query so dashboard listing doesn't need a join.
    query: Mapped[str] = mapped_column(Text, nullable=False)
    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    passed: Mapped[bool] = mapped_column(nullable=False)
    total_findings: Mapped[int] = mapped_column(nullable=False)
    ungrounded_count: Mapped[int] = mapped_column(nullable=False)
    total_citations: Mapped[int] = mapped_column(nullable=False)
    unfaithful_count: Mapped[int] = mapped_column(nullable=False)
    uncited_count: Mapped[int] = mapped_column(nullable=False)
    failure_reasons: Mapped[Optional[list[str]]] = mapped_column(JSONB, nullable=True)
    # Eval judge model + cost (eval/harness.py's faithfulness/completeness/relevance LLM calls).
    eval_model: Mapped[str] = mapped_column(String, nullable=False, server_default="")
    eval_input_tokens: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    eval_output_tokens: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    eval_cost_usd: Mapped[float] = mapped_column(Float, nullable=False, server_default="0")
    # Completeness recall (covered/total subtopics) and relevance score (1-5).
    recall_score: Mapped[float] = mapped_column(Float, nullable=False, server_default="0")
    relevance_score: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    # Source authority: weighted mean over unique cited domains (0-1),
    # primary 1.0 / secondary 0.6 / other 0.2 (eval/source_authority.py).
    authority_score: Mapped[float] = mapped_column(Float, nullable=False, server_default="0")
    # Full eval.schema.EvalReport.model_dump() for the drill-down detail view.
    report: Mapped[dict[str, object]] = mapped_column(JSONB, nullable=False)

    run: Mapped[ResearchRun] = relationship(back_populates="eval_reports")
